### PR TITLE
#208 Detect and log missing plugins that are activated in database table

### LINKED ISSUE #208: Activated plugin which is missing in file system leads to subsequent errors
After merging the last pull requests, somewhen around 2021-08-24 the menus
- administration / user / areas and
- administration / groups / areas
are not accessible anymore. I get a 500 error code when clicking those submenus and have no idea, where the general error might be. It worked (even though in a partially broken manner) with the develop branch before my first pull requests were merged.

Edit: Kind of false alert. For testing purposes, I only switched /contenido folders, BUT the original one had one of my own plugins, whilst the second one didn't have it on file. Therefor, the above mentioned pages crashed with plugin missing. Nevertheless, it's a bit of a bugger that momentarily this error is not caught.

### PR DESCRIPTION
**Pull request by tone2tone**
Problem summary: when swapping contenido folders (e.g. in case of an update/upgrade), it might happen that previously (and still) activated plugins are physically not yet present in the new contenido folder. If so, this causes multiple problems at unexpected places. Some backend menus won't work or don't show their content pages. 
This extended plugin check routine logs error messages if a) a plugin folder for an activated plugin is not there and b) the folder is there, but config.plugin.php is not available, for whatever reason.

### CODE REVIEW

File: contenido/includes/functions.includePluginConf.php [hunk 1]
```diff
@@ -33,6 +33,8 @@
 
         if (is_dir($pluginFolder . $pluginName . '/')) {
             $plugins[] = $pluginName;
+        } else {
+        cWarning(__FILE__, __LINE__, "Plugin <" . $pluginName. "> is activated in database, but folder does not exist. This leads to errors e.g. in user or group rights area settings.");
```
Comment (muratpurc) [inline contenido/includes/functions.includePluginConf.php]: Please indent body of else condition.

File: contenido/includes/functions.includePluginConf.php [hunk 2]
```diff
@@ -48,7 +50,9 @@
 
     if (cFileHandler::exists($pluginConfigFile)) {
         include_once($pluginConfigFile);
-    }
+    } else {
+        cWarning(__FILE__, __LINE__, "Plugin <" . $pluginName. "> configuration file config.plugin.php is missing.");		
+	}
```
Comment (muratpurc) [inline contenido/includes/functions.includePluginConf.php]: Please use whitespaces, not tab.

**Review by muratpurc — CHANGES_REQUESTED** [review]

File: contenido/includes/functions.includePluginConf.php (hunk 2 above)
Comment (tone2tone) [reply contenido/includes/functions.includePluginConf.php]: done! New commit uploaded.

**Comment by gonatan** [comment]
@purcaholic This merged PR is still "In progress" on the Kanban board.
It's probably because you still "request changes". Can you accept these?
I guess the board entry will then move to "Done".
